# Generated by Django 5.2 on 2025-04-03 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Lu', 'Lu'), ('Archivé', 'Archivé')], default='Nouveau', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nutritionniste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Publié', 'Publié'), ('Brouillon', 'Brouillon'), ('Supprimé', 'Supprimé')], default='Publié', max_length=10)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.categorie')),
                ('nutritionniste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.nutritionniste')),
            ],
        ),
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Actif', 'Actif'), ('Archivé', 'Archivé')], default='Actif', max_length=10)),
                ('nutritionniste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.nutritionniste')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('statut', models.CharField(choices=[('Confirmé', 'Confirmé'), ('Annulé', 'Annulé'), ('En attente', 'En attente')], default='En attente', max_length=15)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Actif', 'Actif'), ('Annulé', 'Annulé'), ('Terminé', 'Terminé')], default='Actif', max_length=10)),
                ('nutritionniste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.nutritionniste')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.patient')),
            ],
        ),
    ]
